language: python
python:
    - 2.7
sudo: false
cache: pip
addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran
install:
    - pip install -vvvv .
    - pip install coveralls
script:
    - make test
after_success:
    - coveralls
