language: python
python:
    - 2.7
install:
    - sudo apt-get install libblas-dev
    - sudo apt-get install liblapack-dev
    - sudo apt-get install gfortran
    - pip install numpy
    - pip install scipy
    - pip freeze
    - pip install -e .
script:
    - python setup.py test
