language: python
python:
    - 2.7
sudo: false
addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran
install:
    - pip install -vvvv .
    - pip install coveralls
script:
    - coverage run setup.py test
after_success:
    - coveralls
