language: python
python:
    - "2.7_with_system_site_packages"
before_install:
    - sudo apt-get install -qq python-numpy python-scipy
install:
    - python setup.py install
script:
    - python setup.py test
